Add a func to check the WLCG path
opensciencegrid/xrootd-monitoring-collector pull request #33
Opened 2023-03-02 02:31 UTC by biozit

A function to check if a request is WLCG.

2023-03-02 17:57 UTC, ddavila0 commented on Collectors/wlcg_converter.py
> +        path = parts[5]
Just send this line (192) to after the "if" to prevent and out of index error when the "if" statement is true

2023-03-02 17:57 UTC, ddavila0 requested changes
ignore this

2023-03-02 21:50 UTC, ddavila0 commented
LGTM

2023-03-03 03:01 UTC, biozit commented
@djw8605 @jthiltges  could you check this?

2023-03-03 04:41 UTC, jthiltges commented
Did the urllib.parse alternative work out? URL parsing by regex is painful, and it would be nice to avoid it if we can.

```python
import urllib.parse

def tpcPathCheckWLCG(path):
    parts = urllib.parse.urlparse(path)
    path = parts.path.lstrip('/')
    if path.startswith('store') or path.startswith('user/dteam'):
        return True
    else:
        return False
```

2023-03-03 18:12 UTC, biozit commented
The urllib.parse is 11 times faster than the regex!!

2023-03-03 18:17 UTC, biozit commented
@jthiltges how about the code now?

2023-03-03 19:47 UTC, jthiltges requested changes
LGTM aside from the `re` import that is unused

2023-03-03 19:47 UTC, jthiltges commented on Collectors/wlcg_converter.py
> +import re
```suggestion
```

2023-03-03 19:50 UTC, jthiltges approved these changes
LGTM

2023-03-03 20:11 UTC, merged